### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ChrWalte** [ChrWalte/erchive#1]
While running on a drive root, I got the following error:

G:\>erchive . password
panic: open System Volume Information: Access is denied.

goroutine 1 [running]:
main.handleCompression(...)
        C:/Users/christopher/go/src/erchive/main.go:107
main.main()
        C:/Users/christopher/go/src/erchive/main.go:69 +0x3ce`

**Comment by ChrWalte** [comment]
This failed because the program tried to create the unzipped/zipped folder at the root directory. 
In this case: `../`

Since this was tried at the `G:\` directory, it failed as there is no directory above that on windows.
